# Site settings
title: Pensées de Thaui
description: >-
  Un blog sur lequel je partage différentes pensées au jour le jour
url: "https://ypetremann.github.io"
author:
  name: "Thaui"
  email: "TODO"
  url: "TODO"

# Build settings
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page:num/

# baseurl: "/"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-seo-tag
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# theme: minima
excerpt_separator: "<!--more-->"
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
